# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUi2(object):
    def setupUi(self, JarvisUi2):
        JarvisUi2.setObjectName("JarvisUi2")
        JarvisUi2.resize(1386, 703)
        self.centralwidget = QtWidgets.QWidget(JarvisUi2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1381, 701))
        self.label.setStyleSheet("background : HDC-MD-04;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 130, 591, 441))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("mid2.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 60, 431, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Jarv0.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1070, 190, 271, 431))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("robo4.gif"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 130, 261, 111))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("fun2.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 340, 261, 111))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("fun2.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(120, 370, 181, 61))
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
"border-radius: none;\n"
"color: cyan;\n"
"font:32px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(120, 160, 181, 61))
        self.textBrowser_2.setStyleSheet("background-color: transparent;\n"
"border-radius: none;\n"
"color: cyan;\n"
"font:32px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(390, 620, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Start.setFont(font)
        self.Start.setStyleSheet("background-color:#003152;\n"
"color: rgb(128, 255, 0);")
        self.Start.setObjectName("Start")
        self.Start_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Start_2.setGeometry(QtCore.QRect(880, 620, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Start_2.setFont(font)
        self.Start_2.setStyleSheet("background: #003152;\n"
"color:#FE2712;")
        self.Start_2.setObjectName("Start_2")
        JarvisUi2.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUi2)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi2)

    def retranslateUi(self, JarvisUi2):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi2.setWindowTitle(_translate("JarvisUi2", "MainWindow"))
        self.label.setText(_translate("JarvisUi2", "TextLabel"))
        self.Start.setText(_translate("JarvisUi2", "Start"))
        self.Start_2.setText(_translate("JarvisUi2", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUi2 = QtWidgets.QMainWindow()
    ui = Ui_JarvisUi2()
    ui.setupUi(JarvisUi2)
    JarvisUi2.show()
    sys.exit(app.exec_())
